window.TYPE_IIS_ENZYMES = [
  { name: 'AcuI', recognition: 'CTGAAG', cut: { kind: 'simple', top: 16, bottom: 14 }, subtype: 'IIC' },
  { name: 'AlwI', recognition: 'GGATC', cut: { kind: 'simple', top: 4, bottom: 5 } },
  { name: 'BaeI', recognition: 'ACNNNNGTAYC', cut: { kind: 'dual', leftTop: 10, leftBottom: 15, rightTop: 12, rightBottom: 7 }, subtype: 'IIC' },
  { name: 'BbsI', recognition: 'GAAGAC', cut: { kind: 'simple', top: 2, bottom: 6 }, subtype: 'IIT' },
  { name: 'BbvI', recognition: 'GCAGC', cut: { kind: 'simple', top: 8, bottom: 12 } },
  { name: 'BccI', recognition: 'CCATC', cut: { kind: 'simple', top: 4, bottom: 5 } },
  { name: 'BceAI', recognition: 'ACGGC', cut: { kind: 'simple', top: 12, bottom: 14 } },
  { name: 'BcgI', recognition: 'CGANNNNNNTGC', cut: { kind: 'dual', leftTop: 10, leftBottom: 12, rightTop: 12, rightBottom: 10 }, subtype: 'IIC' },
  { name: 'BciVI', recognition: 'GTATCC', cut: { kind: 'simple', top: 6, bottom: 5 } },
  { name: 'BcoDI', recognition: 'GTCTC', cut: { kind: 'simple', top: 1, bottom: 5 }, subtype: 'IIT', aliases: ['BsmAI'] },
  { name: 'BfuAI', recognition: 'ACCTGC', cut: { kind: 'simple', top: 4, bottom: 8 }, aliases: ['BspMI'] },
  { name: 'BmrI', recognition: 'ACTGGG', cut: { kind: 'simple', top: 5, bottom: 4 } },
  { name: 'BpmI', recognition: 'CTGGAG', cut: { kind: 'simple', top: 16, bottom: 14 }, subtype: 'IIC' },
  { name: 'BpuEI', recognition: 'CTTGAG', cut: { kind: 'simple', top: 16, bottom: 14 }, subtype: 'IIC' },
  { name: 'BsaI', recognition: 'GGTCTC', cut: { kind: 'simple', top: 1, bottom: 5 }, subtype: 'IIT', aliases: ['BsaI-HF v2'] },
  { name: 'BsaXI', recognition: 'ACNNNNNCTCC', cut: { kind: 'dual', leftTop: 9, leftBottom: 12, rightTop: 10, rightBottom: 7 }, subtype: 'IIC' },
  { name: 'BseRI', recognition: 'GAGGAG', cut: { kind: 'simple', top: 10, bottom: 8 }, subtype: 'IIC' },
  { name: 'BsgI', recognition: 'GTGCAG', cut: { kind: 'simple', top: 16, bottom: 14 }, subtype: 'IIC' },
  { name: 'BsmAI', recognition: 'GTCTC', cut: { kind: 'simple', top: 1, bottom: 5 }, subtype: 'IIT', aliases: ['BcoDI'] },
  { name: 'BsmBI', recognition: 'CGTCTC', cut: { kind: 'simple', top: 1, bottom: 5 }, subtype: 'IIT', aliases: ['Esp3I', 'BsmBI-v2'] },
  { name: 'BsmFI', recognition: 'GGGAC', cut: { kind: 'simple', top: 10, bottom: 14 }, subtype: 'IIC' },
  { name: 'BsmI', recognition: 'GAATGC', cut: { kind: 'simple', top: 1, bottom: -1 }, subtype: 'IIT' },
  { name: 'BspCNI', recognition: 'CTCAG', cut: { kind: 'simple', top: 9, bottom: 7 }, subtype: 'IIC' },
  { name: 'BspMI', recognition: 'ACCTGC', cut: { kind: 'simple', top: 4, bottom: 8 }, aliases: ['BfuAI'] },
  { name: 'BspQI', recognition: 'GCTCTTC', cut: { kind: 'simple', top: 1, bottom: 4 }, subtype: 'IIT', aliases: ['SapI', 'BspQI-HF'] },
  { name: 'BsrDI', recognition: 'GCAATG', cut: { kind: 'simple', top: 2, bottom: 0 }, subtype: 'IIT' },
  { name: 'BsrI', recognition: 'ACTGG', cut: { kind: 'simple', top: 1, bottom: -1 }, subtype: 'IIT' },
  { name: 'BtgZI', recognition: 'GCGATG', cut: { kind: 'simple', top: 10, bottom: 14 }, subtype: 'IIC' },
  { name: 'BtsCI', recognition: 'GGATG', cut: { kind: 'simple', top: 2, bottom: 0 } },
  { name: 'BtsI', recognition: 'GCAGTG', cut: { kind: 'simple', top: 2, bottom: 0 }, subtype: 'IIT', aliases: ['BtsI-v2'] },
  { name: 'BtsIMutI', recognition: 'CAGTG', cut: { kind: 'simple', top: 2, bottom: 0 }, subtype: 'IIT' },
  { name: 'CspCI', recognition: 'CAANNNNNGTGG', cut: { kind: 'dual', leftTop: 11, leftBottom: 13, rightTop: 12, rightBottom: 10 }, subtype: 'IIC' },
  { name: 'EarI', recognition: 'CTCTTC', cut: { kind: 'simple', top: 1, bottom: 4 }, subtype: 'IIT' },
  { name: 'EciI', recognition: 'GGCGGA', cut: { kind: 'simple', top: 11, bottom: 9 }, subtype: 'IIC' },
  { name: 'Esp3I', recognition: 'CGTCTC', cut: { kind: 'simple', top: 1, bottom: 5 }, subtype: 'IIT', aliases: ['BsmBI'] },
  { name: 'FauI', recognition: 'CCCGC', cut: { kind: 'simple', top: 4, bottom: 6 } },
  { name: 'FokI', recognition: 'GGATG', cut: { kind: 'simple', top: 9, bottom: 13 } },
  { name: 'HgaI', recognition: 'GACGC', cut: { kind: 'simple', top: 5, bottom: 10 } },
  { name: 'HphI', recognition: 'GGTGA', cut: { kind: 'simple', top: 8, bottom: 7 } },
  { name: 'HpyAV', recognition: 'CCTTC', cut: { kind: 'simple', top: 6, bottom: 5 } },
  { name: 'MboII', recognition: 'GAAGA', cut: { kind: 'simple', top: 8, bottom: 7 } },
  { name: 'MlyI', recognition: 'GAGTC', cut: { kind: 'simple', top: 5, bottom: 5 } },
  { name: 'MmeI', recognition: 'TCCRAC', cut: { kind: 'simple', top: 20, bottom: 18 }, subtype: 'IIC' },
  { name: 'MnlI', recognition: 'CCTC', cut: { kind: 'simple', top: 7, bottom: 6 } },
  { name: 'NmeAIII', recognition: 'GCCGAG', cut: { kind: 'simple', top: 21, bottom: 19 }, subtype: 'IIC' },
  { name: 'PaqCI', recognition: 'CACCTGC', cut: { kind: 'simple', top: 4, bottom: 8 } },
  { name: 'PleI', recognition: 'GAGTC', cut: { kind: 'simple', top: 4, bottom: 5 } },
  { name: 'SapI', recognition: 'GCTCTTC', cut: { kind: 'simple', top: 1, bottom: 4 }, subtype: 'IIT', aliases: ['BspQI'] },
  { name: 'SfaNI', recognition: 'GCATC', cut: { kind: 'simple', top: 5, bottom: 9 } }
];
